

CREATE VIEW [stg].[vwRiskFactorFlowsheets]
AS
	SELECT INPATIENT_DATA_ID
		 , CAST(MAX(FETAL_RF_INTRAUTERINE_RESUSCITATION) AS VARCHAR(500)) AS FETAL_RF_INTRAUTERINE_RESUSCITATION
		 , CAST(MIN(FETAL_RF_INTRAUTERINE_RESUSCITATION_DT) AS VARCHAR(500)) AS FETAL_RF_INTRAUTERINE_RESUSCITATION_DT
		 , CAST(MIN(MATERNAL_RF_EPIDURAL_DT) AS VARCHAR(500)) AS MATERNAL_RF_EPIDURAL_DT
	FROM dbo.tFlowsheets
	GROUP BY INPATIENT_DATA_ID